apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: light-linkerd-demo-app
  labels:
    app: backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: light-linkerd-demo-app
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: python:3.13-alpine
          command: ["python3", "-m", "http.server", "8080"]
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
